#! /bin/sh

set -ex

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
ROOT_DIR="$SCRIPT_DIR"
BUILD_DIR="$ROOT_DIR/build/mlibc-$ARCH"
MLIBC_DIR="$ROOT_DIR/mlibc"
MLIBC_PATCH="$ROOT_DIR/assets/mlibc.patch"

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"

cat <<EOF >cc
#! /bin/sh
$CC $CFLAGS "\$@"
EOF
chmod +x cc
unset CC
unset CFLAGS

cat <<EOF >c++
#! /bin/sh
$CXX $CXXFLAGS "\$@"
EOF
chmod +x c++
unset CXX
unset CXXFLAGS

export PATH="$(pwd -P):$PATH"

cat <<EOF >cross_file.txt
[binaries]
c = 'cc'
cpp = 'c++'

[host_machine]
system = 'template'
cpu_family = '$ARCH'
cpu = '$ARCH'
endian = 'little'
EOF
unset ARCH

git -C "$MLIBC_DIR" apply "$MLIBC_PATCH" 2>/dev/null || \
git -C "$MLIBC_DIR" apply -R --check "$MLIBC_PATCH" >/dev/null

meson setup "$MLIBC_DIR" \
    --cross-file cross_file.txt \
    --buildtype=debug \
    --prefix="$(pwd -P)"/prefix \
    -Ddefault_library=static \
    -Dlibgcc_dependency=false \
    -Duse_freestnd_hdrs=enabled

ninja -v
ninja install
